name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: RKVST login
        run: |
          echo "CLIENT_ID ${{ secrets.RKVST_CLIENT_ID }}"
          CLIENT_ID=${{ secrets.RKVST_CLIENT_ID }}
          SECRET=${{ secrets.RKVST_SECRET }}
          # use curl to obtain a temporary access token for api access using our client id and secret
          RESPONSE=$(curl https://app.rkvst.io/archivist/iam/v1/appidp/token \
              --data-urlencode "grant_type=client_credentials"  \
              --data-urlencode "client_id=${CLIENT_ID}" \
              --data-urlencode "client_secret=${SECRET}")
          echo $RESPONSE
          TOKEN=$(echo -n $RESPONSE | jq -r .access_token)
          echo $TOKEN
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
